kind: Deployment
apiVersion: apps/v1
metadata:
    labels:
        app: trainer-pyco2
        stack: frontend
        source: pyco2
    name: trainer-pyco2
    namespace: microservices
spec:
    replicas: 4
    selector:
        matchLabels:
            run: trainer-pyco2
    template:
        metadata:
            labels:
                app: trainer-pyco2
                run: trainer-pyco2
                source: pyco2
        spec:
            containers:
                -   image: 465848653329.dkr.ecr.us-west-2.amazonaws.com/trainer-pyco2
                    name: trainer-pyco2
                    ports:
                        -   name: web
                            containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
    labels:
        app: trainer-pyco2-service
    name: trainer-pyco2-service
    namespace: microservices
spec:
    selector:
        source: pyco2
        app: trainer-pyco2
    ports:
        -   name: web
            protocol: TCP
            port: 30201
            targetPort: 8080

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    name: pyco2-ingress
    namespace: microservices
spec:
    rules:
        -   http:
                paths:
                    -   path: /pyco2(/|$)(.*)
                        backend:
                            serviceName: trainer-pyco2-service
                            servicePort: 30201


